account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from . import views
from .forms import (UserLoginForm, PwdResetForm, PwdResetConfirmForm)

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),
    # reset password
    path('password_reset/',
         auth_views.PasswordResetView.as_view(template_name='account/password_reset/password_reset_form.html',
                                              success_url='password_reset_email_confirm',
                                              email_template_name='account/password_reset/password_reset_email.html',
                                              form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html',
                                                     success_url='password_reset_complete/',
                                                     form_class=PwdResetConfirmForm
                                                     ), name='password_reset_confirm'),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'),

    path('password_reset_confirm/<uidb64>/password_reset_complete/',
         TemplateView.as_view(template_name='account/password_reset/reset_status.html'),
         name='password_reset_complete'),
    # dashboard dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name='account/dashboard/delete_confirm.html'),
         name='delete_confirm'),

    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("delivery_address/edit/<slug:id>/", views.edit_address, name="edit_address-delivery"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),

    path('wishlist', views.wishlist, name='wishlist'),
    path('wishlist/add_to_wishlist/<int:id>', views.add_to_wishlist, name='user_wishlist'),

    path('save_list/', views.save_list, name='save_list'),
    path('save_list/add_to_wishlist/', views.user_save_list, name='user_save_list'),
    path('save_list/edit_title/<int:id>/', views.edit_title_save, name='edit_title_save'),
    path('save_list/delete_save/<int:id>/', views.delete_save, name='delete_save'),

    path('user_orders/', views.user_orders, name='user_orders'),

    path('user_not_orders/', views.user_not_orders, name='user_not_orders'),

    path("user_not_orders/delete/<int:id>/", views.delete_order, name="delete_order"),

    path('user_orders/rating/<int:id>/', views.rating, name='rating'),
    path('user_orders/rating/<int:id>/<int:rate>', views.rating_ditgis, name='rating_disgis'),

    path('user_orders/val_order/<int:id>/', views.val_order, name='val_order'),

]

checkout/urls.py
from django.urls import path

from . import views

app_name = 'checkout'

urlpatterns = [
    path('delivery_choices', views.delivery_choices, name='delivery_choices'),
    path('basket_update_delivery/', views.basket_update_delivery, name='basket_update_delivery'),
    path('delivery_address/', views.delivery_address, name='delivery_address'),
    path('payment_selection/', views.payment_selection, name='payment_selection'),
    path('payment_complete/', views.payment_complete, name='payment_complete'),
    path('payment_successful/', views.payment_successful, name='payment_successful'),
    path('post_paid/', views.post_paid, name='post_paid'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='index'),
    path('search_img/', views.home_img, name='index_img'),
    path('product/', views.product_all, name='product_all'),
    path('<slug:slug>/<int:category_id>/', views.product_detail, name='product_detail'),
    path('shop/<slug:category_slug>/', views.category_list, name='category_list'),
    path('search_result/', views.search, name='search'),
    path('search_result/img', views.search_img, name='search_img'),
    path('display/', views.display, name='display'),
]

checkout/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class DeliveryOptions(models.Model):
    """
    The Delivery methods table contining all delivery
    """

    DELIVERY_CHOICES = [
        ('IS', 'In Store'),
        ('HD', 'Home Delivery'),
        ('DD', 'Digital Delivery'),
    ]

    delivery_name = models.CharField(
        verbose_name=_('delivery_name'),
        help_text=_('Required'),
        max_length=255
    )

    delivery_price = models.DecimalField(
        verbose_name=_('delivery price'),
        help_text=_('Maximum 1.000.000'),
        error_messages={
            'name': {
                'max_length': _('The price must be between 0 and 99999.999'),
            },

        },

        max_digits=8,
        decimal_places=3,
    )

    delivery_method = models.CharField(
        choices=DELIVERY_CHOICES,
        verbose_name=_('delivery method'),
        help_text=_('Required'),
        max_length=255,
    )
    delivery_timeframe = models.CharField(
        verbose_name=_('delivery timeframe'),
        help_text=_('Required'),
        max_length=255,
    )

    delivery_window = models.CharField(
        verbose_name=_('delivery window'),
        help_text=_('Required'),
        max_length=255,
    )
    order = models.IntegerField(verbose_name=_('list order'), help_text=_('Required'), default=0)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _('Delivery Option')
        verbose_name_plural = _('Delivery Options')

    def __str__(self):
        return self.delivery_name


class PaymentSelections(models.Model):
    """
    Store payment options
    """

    name = models.CharField(
        verbose_name=_('name'),
        help_text=_('Required'),
        max_length=255,
    )

    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = _('Payment Selection')
        verbose_name_plural = _('Payment Selections')

    def __str__(self):
        return self.name

checkout/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render

from account.models import Address
from basket.basket import Basket
from orders.models import OrderItem, Order
from .models import DeliveryOptions


@login_required
def delivery_choices(request):
    delivery_options = DeliveryOptions.objects.filter(is_active=True)
    return render(request, "checkout/delivery_choices.html", {"deliveryoptions": delivery_options})


@login_required
def basket_update_delivery(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        delivery_option = int(request.POST.get('deliveryoption'))
        delivery_type = DeliveryOptions.objects.get(id=delivery_option)
        updated_total_price = basket.basket_update_delivery(delivery_type.delivery_price)

        session = request.session
        if 'purchase' not in request.session:
            session['purchase'] = {
                'delivery_id': delivery_type.id,
            }
        else:
            session['purchase']['delivery_id'] = delivery_type.id
            session.modified = True

        response = JsonResponse({'total': updated_total_price, 'delivery_price': delivery_type.delivery_price})
        return response


@login_required
def delivery_address(request):
    session = request.session
    if 'purchase' not in request.session:
        messages.success(request, 'Vui lòng chọn cài đặt giao hàng')
        return HttpResponseRedirect(request.META['HTTP_REFERER'])

    addresses = Address.objects.filter(customer=request.user).order_by("-default")
    if addresses:
        if 'address' not in request.session:
            session['address'] = {'address_id': str(addresses[0].id)}
        else:
            session['address']['address_id'] = str(addresses[0].id)
            session.modified = True

    return render(request, 'checkout/delivery_address.html', {'addresses': addresses})


@login_required
def post_paid(request):
    basket = Basket(request)
    addresses = Address.objects.filter(customer=request.user).order_by("-default")
    session = request.session
    delivery_option = session['purchase']['delivery_id']
    delivery_type = DeliveryOptions.objects.get(id=delivery_option)
    total_paid = basket.basket_update_delivery(delivery_type.delivery_price)
    order = Order.objects.create(
        user_id=request.user.id,
        full_name=str(addresses[0].full_name),
        email=request.user.email,
        address1=str(addresses[0].address_line),
        address2=str(addresses[0].address_line2),
        postal_code=addresses[0].postcode,
        city=addresses[0].town_city,
        phone=addresses[0].phone,
        total_paid=total_paid,
        # order_key="",
        payment_option="Post-paid",
        billing_status=False,
    )
    order_id = order.pk

    for item in basket:
        OrderItem.objects.create(order_id=order_id, product=item["product"], price=item["price"], quantity=item["qty"])

    basket = Basket(request)
    basket.clear()
    return render(request, "checkout/poin_paid_successful.html", {})


@login_required
def payment_selection(request):
    session = request.session
    if 'address' not in request.session:
        messages.success(request, 'Vui lòng chọn cài đặt địa chỉ')
        return HttpResponseRedirect(request.META['HTTP_REFERER'])

    return render(request, 'checkout/payment_selection.html', {})


####
# PayPay
####
from paypalcheckoutsdk.orders import OrdersGetRequest
from .paypal import PayPalClient


@login_required
def payment_complete(request):
    PPClient = PayPalClient()

    body = json.loads(request.body)
    data = body["orderID"]
    user_id = request.user.id

    requestorder = OrdersGetRequest(data)
    response = PPClient.client.execute(requestorder)

    total_paid = response.result.purchase_units[0].amount.value

    basket = Basket(request)
    order = Order.objects.create(
        user_id=user_id,
        full_name=response.result.purchase_units[0].shipping.name.full_name,
        email=response.result.payer.email_address,
        address1=response.result.purchase_units[0].shipping.address.address_line_1,
        address2=response.result.purchase_units[0].shipping.address.admin_area_2,
        postal_code=response.result.purchase_units[0].shipping.address.postal_code,
        city=response.result.purchase_units[0].shipping.address.country_code,
        phone="0",
        total_paid=response.result.purchase_units[0].amount.value,
        # order_key=response.result.id,
        payment_option="paypal",
        billing_status=True,
    )
    order_id = order.pk

    for item in basket:
        OrderItem.objects.create(order_id=order_id, product=item["product"], price=item["price"], quantity=item["qty"])

    return JsonResponse("Payment completed!", safe=False)


# @login_required
# def payment_complete(request):

@login_required
def payment_successful(request):
    basket = Basket(request)
    basket.clear()
    return render(request, "checkout/payment_successful.html", {})

templates/checkout/delivery_address.html
{% extends "product_base.html" %}
{% load static %}
{% block stylesheet %}
    {% static 'basket/css/basket.css' %}
{% endblock %}
{% block title %}Lựa chọn địa chỉ{% endblock %}
{% block content %}

    <div class="body-basket">
        <div class="grid">
            <div class="container-basket">
                <div class="basket__title">
                    <h1>Địa chỉ giao hàng</h1>
                    <p>Vui lòng chọn <span>địa chỉ giao hàng</span> của bạn</p>
                </div>
                <div class="row">
                    {% if addresses|length == 0 %}
                        <div class="col l-12 m-12 c-12">Không có địa chỉ giao hàng. Thêm địa chỉ <a
                                href="{% url 'account:add_address' %}">tại đây</a>
                        </div>
                    {% else %}
                        <div class="col l-7 m-12 c-12">
                            {% for address in addresses %}
                                {% if not address.default %}
                                    <h1 class="addresses__wrapper-title">Địa chỉ khác</h1>
                                {% endif %}
                                <div class="addresses__wrapper set">
                                    <div class="addresses__body">
                                        <p class="addresses__body-header">
                                            {% if address.default %}
                                                Mặc định
                                            {% endif %}
                                            &nbsp;
                                        </p>
                                        <ul class="addresses__body-list">
                                            <li class="addresses__body-item">
                                                <span>Tên đầy đủ: </span>{{ address.full_name }}</li>
                                            <li class="addresses__body-item">
                                                <span>Địa chỉ 1: </span>{{ address.address_line }}</li>
                                            <li class="addresses__body-item">
                                                <span>Địa chỉ 2: </span>{{ address.address_line2 }}</li>
                                            <li class="addresses__body-item">
                                                <span>Nhận dạng: </span>{{ address.town_city }}</li>
                                            <li class="addresses__body-item">
                                                <span>Mã bưu điện </span>{{ address.postcode }}</li>
                                            <li class="addresses__body-item">
                                                <span>Số điện thoại: </span> {{ address.phone }}</li>
                                        </ul>
                                        <div class="addresses__body-footer">
                                            <a href="{% url 'account:edit_address-delivery' address.id %}">Chỉnh
                                                sửa</a><span>|</span>
                                            {% if not address.default %}
                                                <a href="{% url 'account:set_default' address.id %}"
                                                   class="text-decoration-none">Mặc định</a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>

                        <div class="col l-5 m-12 c-12">
                            <div class="delivery_right-wrapper">
                                <div class="delivery_right-highlight">
                                    <div class="delivery_right-highlight-sub">Tổng tiền phụ:</div>
                                    <div class="delivery_right-highlight-text"><span
                                            id="sub_total">{{ basket.get_subtotal_price }}</span><span> Đ</span>
                                    </div>
                                </div>
                                <div class="delivery_right-highlight">
                                    <div class="delivery_right-highlight-sub">Chi phí giao hàng:</div>
                                    <div class="delivery_right-highlight-text"><span
                                            id="delivery_price">{{ basket.get_delivery_price }}</span><span> Đ</span>
                                    </div>
                                </div>
                                <div class="delivery_right-highlight">
                                    <div class="delivery_right-highlight-sub">Tổng tiền:</div>
                                    <div class="delivery_right-highlight-text"><span
                                            id="total">{{ basket.get_total_price }}</span><span> Đ</span>
                                    </div>
                                </div>
                                <a role="button" href="{% url 'checkout:payment_selection' %}"
                                   class="btn btn-white btn-animate"
                                   type="button">Tiếp tục</a>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/checkout/delivery_choices.html
{% extends "product_base.html" %}
{% load static %}
{% block stylesheet %}
    {% static 'basket/css/basket.css' %}
{% endblock %}
{% block title %}Lựa chọn phương thức giao hàng{% endblock %}
{% block content %}

    <div class="body-basket">
        <div class="grid">
            <div class="container-basket">
                <div class="basket__title">
                    <h1>Cài đặt giao hàng</h1>
                    <p>Lựa chọn <span>cách thức giao hàng</span> dành cho bạn</p>
                </div>
                {% if messages %}
                    <div class="log__alert-error" alert-{{ message.tags }} role="alert">
                        {% for message in messages %}
                            {{ message|safe }}
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="row">
                    {% if deliveryoptions|length == 0 %}
                    <div class="col l-12 m-12 c-12">Không có tùy chọn giao hàng <a href="{% url 'store:index' %}">Cửa hàng</a>
                    </div>
                    {% else %}
                    <div class="col l-7 m-12 c-12">
                    {% for option in deliveryoptions %}
                        <label class="delivery_left" for="delivery{{ option.id }}" >
                            <div class="delivery_left-wrapper" data-index="{{option.id}}">
                                <div class="delivery_left-icon">
                                    <i class='bx bxs-truck'></i>
                                </div>
                                <div class="delivery_left-content">
                                    <p class="delivery_left-name">{{option.delivery_name}}</p>
                                    <p class="delivery_left-subname">Đơn đặt hàng của bạn sẽ được giao trong vòng {{option.delivery_timeframe}}</p>
                                </div>
                                <input class="delivery_left-check" type="radio" name="deliveryOption" id="delivery{{ option.id }}" value="{{ option.id }}">
                            </div>
                        </label>
                    {% endfor %}
                    </div>

                    <div class="col l-5 m-12 c-12">
                        <div class="delivery_right-wrapper">
                            <div class="delivery_right-highlight">
                                <div class="delivery_right-highlight-sub">Tổng tiền phụ:</div>
                                <div class="delivery_right-highlight-text"><span
                                        id="sub_total">{{ basket.get_subtotal_price }}</span><span> Đ</span>
                                </div>
                            </div>
                            <div class="delivery_right-highlight">
                                <div class="delivery_right-highlight-sub">Chi phí giao hàng:</div>
                                <div class="delivery_right-highlight-text"><span
                                        id="delivery_price">{{ basket.get_delivery_price }}</span><span> Đ</span>
                                </div>
                            </div>
                            <div class="delivery_right-highlight">
                                <div class="delivery_right-highlight-sub">Tổng tiền:</div>
                                <div class="delivery_right-highlight-text"><span
                                        id="total">{{ basket.get_total_price }}</span><span> Đ</span>
                                </div>
                            </div>
                            <a role="button" href="{% url "checkout:delivery_address" %}"
                               class="btn btn-white btn-animate"
                               type="button">Tiếp tục</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <script>
        $('input[type=radio][name=deliveryOption]').on('change', function (e) {
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: '{% url 'checkout:basket_update_delivery' %}',
                data: {
                    deliveryoption: $(this).val(),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    action: 'post',
                },
                success: function (json) {
                    document.getElementById('total').innerHTML = json.total;
                    document.getElementById('delivery_price').innerHTML = json.delivery_price;
                },
                error: function (xhr, errmsg, err) {
                },
            });
        });
    </script>
{% endblock %}

templates/checkout/payment_selection.html
{% extends "product_base.html" %}
{% load static %}
{% block stylesheet %}
    {% static 'basket/css/basket.css' %}
{% endblock %}
{% block title %}Lựa chọn phương thanh thanh toán{% endblock %}
{% block content %}
    <div class="body-basket">
        <div class="grid">
            <div class="container-basket">
                <div class="basket__title">
                    <h1>Tùy chọn giao hàng</h1>
                    <p>Vui lòng chọn <span>Phương thức giao hàng</span> của bạn</p>
                </div>
                <div class="row">
                    <div class="col l-7 m-12 c-12">
                        <div id="paypal-button-container"></div>
                        <a href="{% url 'checkout:post_paid' %}" class="postpaid-button-container"><p>Thanh toán khi
                            nhận hàng</p></a>
                    </div>
                    <div class="col l-5 m-12 c-12">
                        <div class="delivery_right-wrapper">
                            <div class="delivery_right-highlight">
                                <div class="delivery_right-highlight-sub">Tổng tiền phụ:</div>
                                <div class="delivery_right-highlight-text"><span
                                        id="sub_total">{{ basket.get_subtotal_price }}</span><span> Đ</span>
                                </div>
                            </div>
                            <div class="delivery_right-highlight">
                                <div class="delivery_right-highlight-sub">Chi phí giao hàng:</div>
                                <div class="delivery_right-highlight-text"><span
                                        id="delivery_price">{{ basket.get_delivery_price }}</span><span> Đ</span>
                                </div>
                            </div>
                            <div class="delivery_right-highlight">
                                <div class="delivery_right-highlight-sub">Tổng tiền:</div>
                                <div class="delivery_right-highlight-text"><span
                                        id="total">{{ basket.get_total_price }}</span><span> Đ</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script
            src="https://www.paypal.com/sdk/js?client-id=Adl9_10CxHDSL-VZobkyiOhy49BTN2TvqnvCkSiVcz7hHcxVtiemh1EyOSkRQCBWfgRco8cvDUD9caJK&currency=USD"
            data-sdk-integration-source="button-factory">
    </script>
    <script>
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');


        function initPayPalButton() {
            paypal.Buttons({
                style: {
                    shape: 'rect',
                    color: 'gold',
                    layout: 'vertical',
                    label: 'paypal',

                },
                createOrder: function (data, actions) {
                    return actions.order.create({
                        purchase_units: [{
                            "amount": {
                                "currency_code": "USD",
                                "value": '{{basket.price_convert_vnd|floatformat:2}}'
                            }
                        }]
                    });
                },
                onApprove: function (data) {
                    var url = "{% url 'checkout:payment_complete' %}"
                    return fetch(url, {
                        method: 'POST',
                        headers: {
                            'content-type': 'application/json',
                            'X-CSRFToken': csrftoken,
                        },
                        body: JSON.stringify({
                            orderID: data.orderID
                        })
                    }).then(function () {
                        location.href = '{% url 'checkout:payment_successful' %}';
                    })
                },
            }).render('#paypal-button-container');
        }

        initPayPalButton();

    </script>

{% endblock %}

templates/checkout/payment_successful.html
{% extends "product_base.html" %}
{% block title %}Thanh toán thành công{% endblock %}
{% block content %}

    <style>
        .status__wrapper {
            position: relative;
            width: 100%;
            text-align: center;
        }

        .title-status {
            font-size: 2.6rem;
            font-weight: bold;
            color: var(--border-color);
            line-height: 1.6em;
            text-align: center;
        }

        .title-status__text {
            font-size: 1.6rem;
            color: #333;
            line-height: 1.6em;
            text-align: center;
            margin: 10px 0;
        }
        .title-status__link{
            margin-bottom: 10px;
        }

    </style>

    <div class="status__wrapper">
        <h3 class="title-status">Thanh toán thành công</h3>
        <p class="title-status__text">Đơn hàng của bạn đã hoàn tất.
        </p>
        <a class="title-status__link btn btn-white btn-animate" href="{% url 'account:user_orders' %}">Xem lại đơn hàng</a>
    </div>
{% endblock %}

templates/checkout/poin_paid_successful.html
{% extends "product_base.html" %}
{% block title %}Thanh toán thành công{% endblock %}
{% block content %}

<style>
        .status__wrapper {
            position: relative;
            width: 100%;
            text-align: center;
        }

        .title-status {
            font-size: 2.6rem;
            font-weight: bold;
            color: var(--border-color);
            line-height: 1.6em;
            text-align: center;
        }

        .title-status__text {
            font-size: 1.6rem;
            color: #333;
            line-height: 1.6em;
            text-align: center;
            margin: 10px 0;
        }

        .title-status__link{
            margin-bottom: 10px;
        }

    </style>

    <div class="status__wrapper">
            <h3 class="title-status">Đặt hàng thành công.</h3>
            <p class="title-status__text">Đơn hàng đang được xử lí trong ít phút</p>
            <p class="title-status__text">Việc thanh toán sẽ hoàn thành cho đến khi bạn đã nhận được hàng</p>
            <a class="title-status__link btn btn-white btn-animate" href="{% url 'account:user_not_orders' %}">Xem lại đơn hàng </a>
    </div>
{% endblock %}